### ISSUE TITLE
Error on page load

### ISSUE THREAD

**Issue by yashha** [yunity/yunity-MVP-proposal-AngularMaterial#1]
Idk if you still working on this but there is an error if I load the page. :)

![image](https://cloud.githubusercontent.com/assets/4728786/17120126/7e51676e-52ca-11e6-93db-e06de3dac0a0.png)

**Comment by Sneezoo** [comment]
I can see you are trying to use this proposal directly from your computer without any server.
To avoid this you have to deploy this to XAMPP or any webserver to your liking.
